export const GENESIS_PORTAL_STYLES = `
:root{color-scheme:dark;--midnight:#020f21;--ink:#07182d;--ivory:#f4efe4;--copper:#b65c18;--gold:#f5a12a;--line:rgba(245,161,42,.28);font-family:Inter,system-ui,sans-serif;background:var(--midnight);color:var(--ivory)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 70% 10%,rgba(182,92,24,.14),transparent 28rem),var(--midnight);line-height:1.55}a{color:inherit}.site-shell{max-width:1480px;margin:auto;padding:0 4vw}.site-header{min-height:82px;display:flex;align-items:center;gap:2rem;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10;background:rgba(2,15,33,.92);backdrop-filter:blur(18px)}.site-header nav{display:flex;gap:1.5rem;margin-left:auto}.site-header nav a{text-decoration:none;color:rgba(244,239,228,.78)}
.factory-lockup{display:inline-flex;align-items:center;gap:.7rem;text-decoration:none;letter-spacing:.13em}.factory-lockup span:last-child{display:grid}.factory-lockup strong{font-size:1.25rem;line-height:1}.factory-lockup small{font-size:.62rem;color:var(--gold);letter-spacing:.36em}.factory-reference{position:relative;z-index:2;width:min(100%,620px);border:1px solid var(--line);border-radius:1rem;box-shadow:0 24px 70px rgba(0,0,0,.45);object-fit:contain}
.button{display:inline-flex;justify-content:center;padding:.8rem 1.2rem;border-radius:.45rem;background:linear-gradient(135deg,var(--gold),#c8741d);color:#130d06;text-decoration:none;font-weight:750;border:1px solid var(--gold)}.button-quiet{background:transparent;color:var(--ivory);border-color:var(--line)}.hero{min-height:720px;display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.9fr);align-items:center;gap:5vw;padding:7rem 0}.hero-copy{max-width:720px}.eyebrow{text-transform:uppercase;letter-spacing:.2em;color:var(--gold);font-size:.76rem;font-weight:750}.hero h1{font:700 clamp(3rem,7vw,6.8rem)/.98 "Space Grotesk",Inter,sans-serif;letter-spacing:-.055em;margin:.3em 0}.lede{max-width:650px;color:rgba(244,239,228,.76);font-size:clamp(1.05rem,2vw,1.35rem)}.actions{display:flex;gap:.8rem;margin-top:2rem}.factory-orbit{min-height:440px;display:grid;place-items:center;position:relative}.orbit{position:absolute;border:1px solid var(--line);border-radius:50%;width:100%;height:45%;transform:rotate(-8deg)}.orbit-two{transform:rotate(13deg);width:80%}
.section{padding:6rem 0;border-top:1px solid var(--line)}.section>h2{font:650 clamp(2rem,4vw,3.8rem)/1.08 "Space Grotesk",Inter,sans-serif;max-width:850px;margin:.25em 0 1em}.application-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.2rem}.application-card{display:grid;grid-template-columns:minmax(200px,.8fr) 1fr;min-height:390px;border:1px solid color-mix(in srgb,var(--app-accent),transparent 45%);border-radius:1.25rem;overflow:hidden;background:linear-gradient(140deg,var(--app-surface),#071220);color:var(--app-text)}.application-brand{padding:1.25rem;display:grid;place-items:center;background:rgba(0,0,0,.3)}.application-brand img{display:block;width:100%;max-height:330px;object-fit:contain;border-radius:.65rem}.application-copy{padding:clamp(1.5rem,3vw,3rem);align-self:center}.application-copy h3{font-size:clamp(1.6rem,3vw,2.7rem);line-height:1.05;margin:.35em 0}.application-copy p{color:color-mix(in srgb,var(--app-text),transparent 22%)}.application-copy a{color:var(--app-accent);font-weight:750;text-decoration:none}.audience{font-size:.9rem}.steps{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:1px;background:var(--line);border:1px solid var(--line);border-radius:1rem;overflow:hidden}.steps article{background:var(--ink);padding:2rem 1.3rem;min-height:240px}.steps span{color:var(--gold);font-weight:800}.steps h3{font-size:1.25rem}.steps p{color:rgba(244,239,228,.67);font-size:.93rem}footer{display:grid;grid-template-columns:1fr 2fr auto;align-items:center;gap:2rem;padding:3rem 0;border-top:1px solid var(--line);color:rgba(244,239,228,.66);font-size:.88rem}
@media(max-width:980px){.site-header nav{display:none}.site-header .button{margin-left:auto}.hero{min-height:auto;grid-template-columns:1fr;padding:5rem 0}.factory-orbit{min-height:360px;grid-row:1}.application-grid{grid-template-columns:1fr}.steps{grid-template-columns:repeat(2,minmax(0,1fr))}.steps article:last-child{grid-column:1/-1}footer{grid-template-columns:1fr}}
@media(max-width:640px){.site-shell{padding:0 1rem}.site-header{min-height:70px}.site-header>.button{font-size:.8rem;padding:.65rem}.hero{padding:3.5rem 0}.factory-orbit{min-height:260px}.application-card{grid-template-columns:1fr}.application-brand{max-height:280px}.application-copy{padding:1.5rem}.steps{grid-template-columns:1fr}.steps article:last-child{grid-column:auto}.actions{align-items:stretch;flex-direction:column}.section{padding:4rem 0}footer{align-items:start}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
`;
