import { MissionControlSnapshot } from "../production-runtime";

export function renderMissionControl(initial: MissionControlSnapshot): string {
    const data = JSON.stringify(initial).replaceAll("<", "\\u003c");
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#020f21"><title>PBOS Genesis Mission Control</title><style>
:root{color-scheme:dark;--bg:#020913;--panel:#08131f;--line:#81501f;--gold:#e6a632;--text:#f8f3e8;--muted:#aeb8c2;--ok:#8ed36f;--warn:#ffbf55;--bad:#ff7373}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#10263b 0,transparent 38%),var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,sans-serif}header,main{width:min(1440px,calc(100% - 32px));margin:auto}header{padding:22px 0;display:flex;justify-content:space-between;gap:16px;align-items:center;border-bottom:1px solid var(--line)}h1,h2,p{margin:0}.brand{color:var(--gold);letter-spacing:.16em}.status{padding:8px 13px;border:1px solid currentColor;border-radius:999px;font-weight:800}.grid{display:grid;grid-template-columns:1.4fr 1fr;gap:16px;padding:18px 0}.panel{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid #243446;border-radius:16px;padding:18px;box-shadow:0 18px 55px #0005}.wide{grid-column:1/-1}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.fact{padding:12px;background:#040b13;border:1px solid #1d2c3c;border-radius:10px}.fact small{display:block;color:var(--muted)}.fact strong{display:block;margin-top:4px;overflow-wrap:anywhere}.timeline{list-style:none;padding:0;margin:14px 0 0;max-height:460px;overflow:auto}.timeline li{padding:12px 0 12px 20px;border-left:2px solid var(--line);position:relative}.timeline li:before{content:"";position:absolute;width:9px;height:9px;border-radius:50%;background:var(--gold);left:-5.5px;top:18px}.timeline time,.muted{color:var(--muted)}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:9px;border-bottom:1px solid #253445}button,a.button{background:var(--gold);color:#150d03;border:0;border-radius:8px;padding:10px 14px;font-weight:800}.disconnected{color:var(--bad)}@media(max-width:850px){.grid{grid-template-columns:1fr}.facts{grid-template-columns:1fr 1fr}.wide{grid-column:auto}}@media(max-width:480px){.facts{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style></head><body><header><div><div class="brand">PBOS GENESIS</div><h1>Mission Control</h1></div><div id="connection" class="status" role="status" aria-live="polite">CONNECTED</div></header><main><div class="grid">
<section class="panel wide" aria-labelledby="active-title"><h2 id="active-title">Active Build</h2><div id="active"></div></section>
<section class="panel"><h2>Live Activity</h2><ol id="events" class="timeline" aria-live="polite" aria-relevant="additions"></ol></section>
<section class="panel"><h2>Health & Metrics</h2><div id="health"></div></section>
<section class="panel"><h2>Application Previews</h2><div id="preview"></div></section>
<section class="panel"><h2>Build Evidence</h2><div id="evidence"></div></section>
<section class="panel wide"><h2>Historical Runs</h2><div id="history"></div></section>
<section class="panel wide"><h2>Next Action</h2><div id="next"></div></section></div></main>
<script>let state=${data};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const duration=ms=>{const s=Math.max(0,Math.floor(ms/1000));return s<60?s+'s':Math.floor(s/60)+'m '+s%60+'s'};
function render(s){state=s;const run=s.activeRun,stage=s.activeStage,lease=s.activeLease;document.getElementById('connection').textContent=s.connection+' · '+s.status;document.getElementById('connection').className='status '+(s.connection==='CONNECTED'?'':'disconnected');
document.getElementById('active').innerHTML=run?'<p><strong>BUILD ACTIVE</strong> · '+esc(run.selectedMission)+'</p><div class="facts"><div class="fact"><small>Run</small><strong>'+esc(run.runId)+'</strong></div><div class="fact"><small>Status</small><strong>'+esc(run.status)+'</strong></div><div class="fact"><small>Stage</small><strong>'+esc(stage?.title??'Transitioning')+'</strong></div><div class="fact"><small>Elapsed</small><strong id="elapsed" data-start="'+esc(run.startedAt)+'">'+duration(Date.now()-Date.parse(run.startedAt))+'</strong></div><div class="fact"><small>Heartbeat</small><strong>'+duration(Date.now()-Date.parse(run.lastHeartbeatAt))+' ago</strong></div><div class="fact"><small>Branch</small><strong>'+esc(run.currentBranch)+'</strong></div><div class="fact"><small>Commit</small><strong>'+esc(run.currentCommit)+'</strong></div><div class="fact"><small>Lease</small><strong>'+esc(lease?.status??'MISSING')+'</strong></div></div>':'<p><strong>PBOS IDLE</strong></p><p class="muted">Last result: '+esc(s.lastRun?.terminalSummary??'No production run recorded.')+'</p>';
document.getElementById('events').innerHTML=s.recentEvents.map(x=>'<li><strong>'+esc(x.type)+'</strong><br>'+esc(x.summary)+'<br><time>'+esc(x.timestamp)+'</time></li>').join('')||'<li>No execution events yet.</li>';
document.getElementById('health').innerHTML='<p><strong>'+esc(s.health.health)+'</strong></p><table><tbody>'+s.health.components.map(x=>'<tr><th>'+esc(x.component)+'</th><td>'+esc(x.health)+'</td><td>'+esc(x.detail)+'</td></tr>').join('')+'</tbody></table><div class="facts"><div class="fact"><small>Runs</small><strong>'+s.metrics.runsStarted+'</strong></div><div class="fact"><small>Certified</small><strong>'+Math.round(s.metrics.certificationRate*100)+'%</strong></div><div class="fact"><small>Queue</small><strong>'+s.metrics.queueDepth+'</strong></div><div class="fact"><small>Stale leases</small><strong>'+s.metrics.staleLeaseCount+'</strong></div></div>';
const previews=s.applicationPreviews??[];document.getElementById('preview').innerHTML=previews.length?previews.map(p=>'<article class="fact"><small>'+esc(p.systemId)+'</small><strong>'+esc(p.systemName)+'</strong><p>'+esc(p.status)+' · '+esc(p.label)+'</p><p class="muted">'+esc(p.repository)+'@'+esc(p.commit)+'</p>'+(p.webUrl?'<p><a class="button" href="'+esc(p.webUrl)+'">Open '+esc(p.systemName)+' desktop web app</a></p>':'<p class="muted">Desktop web link pending.</p>')+(p.mobileUrl?'<p><a class="button" href="'+esc(p.mobileUrl)+'">Open '+esc(p.systemName)+' mobile app</a></p>':'<p class="muted">Mobile link pending.</p>')+'</article>').join(''):'<p>No exact-revision live application previews yet.</p>';
const evidenceRun=run??s.lastRun;document.getElementById('evidence').innerHTML=evidenceRun?'<div class="facts"><div class="fact"><small>Added</small><strong>'+evidenceRun.filesAdded.length+'</strong></div><div class="fact"><small>Modified</small><strong>'+evidenceRun.filesModified.length+'</strong></div><div class="fact"><small>Deleted</small><strong>'+evidenceRun.filesDeleted.length+'</strong></div><div class="fact"><small>Validations</small><strong>'+evidenceRun.validationResults.length+'</strong></div></div><p class="muted">Evidence IDs: '+esc(evidenceRun.evidenceIds.join(', ')||'None recorded')+'</p>':'<p>No run evidence recorded.</p>';
document.getElementById('history').innerHTML='<table><thead><tr><th>Run</th><th>Mission</th><th>Status</th><th>Duration</th><th>Commit</th></tr></thead><tbody>'+s.history.map(x=>'<tr><td>'+esc(x.runId)+'</td><td>'+esc(x.selectedMission)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.durationMs===undefined?'active':duration(x.durationMs))+'</td><td>'+esc(x.currentCommit)+'</td></tr>').join('')+'</tbody></table>';
document.getElementById('next').innerHTML=s.nextMission?'<p><strong>'+esc(s.nextMission.title)+'</strong></p><p>'+esc(s.nextMission.rationale)+'</p><p>Approval required: '+(s.nextMission.approvalRequired?'YES':'NO')+'</p>':'<p>No eligible mission. PBOS will stop safely until the queue changes.</p>'}
render(state);setInterval(()=>{const n=document.getElementById('elapsed');if(n)n.textContent=duration(Date.now()-Date.parse(n.dataset.start))},1000);setInterval(async()=>{try{const r=await fetch('/api/mission-control/status',{cache:'no-store'});if(!r.ok)throw Error();render(await r.json())}catch{document.getElementById('connection').textContent='DISCONNECTED · STATE UNKNOWN';document.getElementById('connection').className='status disconnected'}},2000);
</script></body></html>`;
}
