import { ApplicationScaffoldGenerator } from "../application-scaffold";
import { GenesisBuildPlan, GenesisBuildPlanCompiler } from "../build-planning";
import { GitHubRepositoryGateway, PullRequestReference, RepositoryReference } from "../platform";
import { createBulletproofBlueprint } from "../reference-systems";
import { SystemBlueprint } from "../system-blueprint";
import { GenesisBuildSession } from "./genesis-control-plane";
import { ActionRisk, BuildAction, BuildAuthorityDecision } from "../autonomous-authority";

export interface PreparedApplicationBuild {
    readonly plan: GenesisBuildPlan;
    readonly branch: string;
    readonly pullRequest: PullRequestReference;
}

export class GenesisWorkflowService {
    constructor(
        private readonly gateway: GitHubRepositoryGateway,
        private readonly planner = new GenesisBuildPlanCompiler(),
        private readonly scaffolds = new ApplicationScaffoldGenerator(),
        private readonly authorize?: (session: GenesisBuildSession, action: BuildAction, risk: ActionRisk, branch: string) => BuildAuthorityDecision
    ) {}

    async inspectAndPlan(session: GenesisBuildSession): Promise<GenesisBuildPlan> {
        const reference = this.reference(session);
        this.requireAuthority(session, "INSPECT_REPOSITORY", "LOW", `agent/plan-${session.system.systemId.toLowerCase()}`);
        this.requireAuthority(session, "CREATE_BUILD_PLAN", "LOW", `agent/plan-${session.system.systemId.toLowerCase()}`);
        const blueprint = this.blueprint(session.system.systemId);
        return this.planner.compile(blueprint, await this.gateway.inspectRepository(reference));
    }

    async prepareDraftBuild(session: GenesisBuildSession): Promise<PreparedApplicationBuild> {
        if (session.grant.mode === "READ_ONLY") throw new Error("Read-only sessions cannot prepare application builds.");
        const reference = this.reference(session);
        const plan = await this.inspectAndPlan(session);
        if (plan.status !== "READY_FOR_APPROVAL") throw new Error(`Build plan blocked: ${plan.blockers.join("; ")}`);
        const branch = `agent/pbos-${session.system.systemId.toLowerCase()}-vertical-slice`;
        for (const [action, risk] of [
            ["PROPOSE_CHANGE", "MEDIUM"], ["MODIFY_APPLICATION_CODE", "MEDIUM"], ["CREATE_TESTS", "MEDIUM"],
            ["CREATE_COMMIT", "MEDIUM"], ["PUSH_BRANCH", "MEDIUM"], ["OPEN_DRAFT_PR", "MEDIUM"]
        ] as readonly (readonly [BuildAction, ActionRisk])[]) this.requireAuthority(session, action, risk, branch);
        await this.gateway.createBranch(reference, branch, plan.repositoryRevision);
        const scaffold = this.scaffolds.generate({ blueprint: plan.blueprint, includeFirstVerticalSlice: true });
        const materialized = await this.scaffolds.materialize(scaffold, {
            writeFiles: files => this.gateway.applyChange(reference, files).then(() => undefined),
            prepareDependencyLock: () => this.gateway.prepareDependencyLock(reference)
        });
        const revision = await this.gateway.commit(reference, "feat: scaffold PBOS legacy planning vertical slice", materialized.generatedPaths);
        await this.gateway.push(reference, branch);
        const pullRequest = await this.gateway.openDraftPullRequest(reference, branch,
            "feat: scaffold PBOS legacy planning vertical slice",
            `Generated by PBOS Genesis from blueprint ${plan.blueprintId} at repository revision ${plan.repositoryRevision}.\n\nValidation and certification remain human-controlled gates.\n\nGenerated commit: ${revision}`);
        return { plan, branch, pullRequest };
    }

    authorizeRemediation(session: GenesisBuildSession, branch: string): void {
        for (const [action, risk] of [
            ["MODIFY_APPLICATION_CODE", "MEDIUM"], ["CREATE_TESTS", "MEDIUM"], ["CREATE_COMMIT", "MEDIUM"], ["PUSH_BRANCH", "MEDIUM"]
        ] as readonly (readonly [BuildAction, ActionRisk])[]) this.requireAuthority(session, action, risk, branch);
    }

    private reference(session: GenesisBuildSession): RepositoryReference {
        const [owner, name] = session.system.repository.split("/");
        if (!owner || !name) throw new Error(`Invalid repository identity: ${session.system.repository}`);
        return { owner, name, defaultBranch: session.system.defaultBranch };
    }

    private blueprint(systemId: string): SystemBlueprint {
        if (systemId === "BULLETPROOF-SYSTEM-001") return createBulletproofBlueprint();
        throw new Error(`No certified build blueprint registered for ${systemId}.`);
    }

    private requireAuthority(session: GenesisBuildSession, action: BuildAction, risk: ActionRisk, branch: string): void {
        if (!this.authorize) return;
        const decision = this.authorize(session, action, risk, branch);
        if (!decision.allowed) throw new Error(`${action} denied: ${decision.reason}`);
    }
}
